# Generated by Django 4.0.3 on 2022-04-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='company',
            new_name='company_name',
        ),
    ]
